### ISSUE TITLE
Bug: doesn't parse tables properly

### ISSUE THREAD

**Issue by rhl-bthr** [sugarlabs/infoslicer#12]
**Steps to reproduce:**
 1. Open the activtiy and search for something in the `Get Article From:` `English Wikipedia`
    Example: `juhu`
 2. The result looks something like - 
![sugar-inforclicer](https://user-images.githubusercontent.com/28059150/35330119-5394aa64-0128-11e8-89b1-78d9a0742a43.jpg)

**Issue:** The table, tr and td tags are not handled properly

**Reproduced on:**
 - rdesktop
 - Sugar 0.112
 - Ubuntu 16.04

**Possible Solutions:**
 1. Design a format to present tables neatly. The amount of text in all cells needs to be taken care, for proper indentation and size of columns.
 2. Ignore tables entirely, as the search says `Get Article From` and this table is mostly a summary of whats given below. 
   This is not preferred as there might be relevant data in other tables.

**Comment by nswarup14** [comment]
@pro-panda 
I did look into the bug that you have described and I believe that the second one, amongst the possible solution that you have listed is actually being implemented.
I managed to take a screen shot as well.

Tested on Ubuntu 18.04, Sugar v0.112 using rDesktop
![screenshot from 2019-03-06 15-27-12](https://user-images.githubusercontent.com/34597895/53872491-64768500-4024-11e9-8bea-296a1b700a89.png)

**Comment by rhl-bthr** [comment]
Thanks, tested again.
I agree
