### ISSUE TITLE
many files have license but no copyright; this renders the license invalid

### ISSUE THREAD

**Issue by quozl** [sugarlabs/infoslicer#15]
Did find this as of head 6ea3d77a4c456ce4df601385647895fadfaeb99e;
* README.md has a copyright and license,
* many source files in the top level directory have license without copyright; which renders their license invalid, requiring users to apply README.md alone,
* most source files in `processing/` and `widgets/` have "Copyright (C) IBM Corporation 2008",
* initial import commit eb4dfd4db9b8ae05ae95f3cfd72ee0bea4145a48 does have source files with "Copyright (C) IBM Corporation 2008", and GPLv2 license file,
* `processing/HTML_strip.py` and `widgets/Journal_Gallery_View.py` are "Copyright (C) Aneesh Dogra <lionaneesh@gmail.com>" (2012, no year), with a GPLv2+ and GPLv3+ license,
* two copies of BeautifulSoup.py are embedded; v3.2.1 and v3.1.0.1,

So what is needed is;
* [x] add a COPYING.GPLv2 (due to license grant in `README.md`, `activity.py`, `book.py`, `bookview.py`, `edit.py`, `library.py`, `net.py`, `setup.py`, `toolbar.py`),
* [ ] add a copyright to the files `activity.py`, `book.py`, `bookview.py`, `edit.py`, `library.py`, `net.py`, `setup.py`, and `toolbar.py`, probably "Copyright (C) IBM Corporation 2008" since it is a derived work, 
* [x] add BSD to license metadata (due to license grant in the two copies of BeautifulSoup.py),

**Comment by vipulgupta2048** [comment]
How should we proceed here?
Should we add the copyright of IBM in those files as done in README?

**Comment by walterbender** [comment]
This code was written by IBM and should be copyright IBM.

**Comment by quozl** [comment]
I've adjusted the issue text, see above.  Please review and comment.

**Comment by vipulgupta2048** [comment]
I am on it, thanks for the detailed assessment @quozl
