### ISSUE TITLE
Misbehaviour of the content box

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/infoslicer#21]
The content box extends beyond the left margin.
![image](https://user-images.githubusercontent.com/35092582/50510170-acba7980-0aae-11e9-9f1c-7212cd822423.png)

**Comment by quozl** [comment]
Tested f1090cfd99b308252338c8893499b5f2d0939252 on Ubuntu 18.04 with Sugar 0.112.  No such problem observed.  Please describe how you cause the problem?

**Comment by Aniket21mathur** [comment]
@quozl  on doing some click events caused the problem for me like switching between articles from Giraffe to Zebra or randomly switching between any of them.I am also  using Ubuntu 18.04.Thanks!

**Comment by quozl** [comment]
@Aniket21mathur, thanks, I've tried that, but nothing goes wrong.  Perhaps it depends on display resolution.  My display resolution is 1024x768.  What is your display resolution?

One way to find out is in Terminal activity;

```
guest@host:~$ xdpyinfo|grep dimensions
```

**Comment by Aniket21mathur** [comment]
@quozl My display resolution is 1360x669 pixels.Thanks!

**Comment by quozl** [comment]
Okay, reproducing that resolution will be impractical, as it is not standard.  Never mind.
