### ISSUE TITLE
Traceback, motion_notify

### ISSUE THREAD

**Issue by quozl** [sugarlabs/infoslicer#23]
```
1546209128.190513 WARNING root: icon_size is deprecated. Use pixel_size instead.
1546209128.192004 WARNING root: icon_size is deprecated. Use pixel_size instead.
Traceback (most recent call last):
  File "/usr/share/sugar/activities/InfoSlicer.activity/infoslicer/widgets/Readonly_Textbox.py", line 131, in motion_notify
    if mouseiter.compare(self.selectionstart) == 1:
AttributeError: 'bool' object has no attribute 'compare'
Traceback (most recent call last):
  File "/usr/share/sugar/activities/InfoSlicer.activity/infoslicer/widgets/Readonly_Textbox.py", line 131, in motion_notify
    if mouseiter.compare(self.selectionstart) == 1:
AttributeError: 'bool' object has no attribute 'compare'

```

**Comment by IamRaviTejaG** [comment]
@quozl `.compare` is a method from which of the imported modules? Is it okay to change the code to
```python
if mouseiter == self.selectionstart:
```
instead?

**Comment by quozl** [comment]
Thanks for looking at this.  I haven't looked at the problem; if I did, I would have fixed it.  But given the error "_object has no attribute_", your suggestion doesn't resemble any patch I've seen for the last ten years.  So just as a wild guess, and again, without my looking at the code, consider for yourself if `mouseiter` always has the expected object type, and ask why would we call a method `compare` on an object of type `bool`.  The latter question perhaps rhetorical.  Answering those questions for yourself will probably lead to better understanding, and then to a solution.  Let us know if you can't progress with that.

**Comment by Aniket21mathur** [comment]
![image](https://user-images.githubusercontent.com/35092582/50619863-faf1d180-0f21-11e9-843f-20282312c4b6.png)
@ImRaviTejaG the error is probably caused if False is returned from get_mouse_iter().So one of the possible solution is to modify  the code in Readonly_Textbox.py  to keep a check for this condition(if False is returned instead of "mouseClickPositionIter").Thanks!

**Comment by quozl** [comment]
Why is False returned by get_mouse_iter()?

**Comment by Aniket21mathur** [comment]
@quozl Can you please tell how to reproduce this error? I can make any further comments only after knowing how the error is actually produced?
Thanks!

**Comment by quozl** [comment]
No, I don't know how it was produced.  I used the activity features a few times.  Then when I looked at the log, I found the error.  You might look at the traceback to find what feature was being used.  In particular look at the functions and line numbers in the stack above the point of failure.  For each line of code, deduce the intention and test all assumptions.
