### ISSUE TITLE
Side toolbar overlays the screen

### ISSUE THREAD

**Issue by rhl-bthr** [sugarlabs/infoslicer#24]
Moved from [Sugar/#763](https://github.com/sugarlabs/sugar/issues/763),

> Info Slicer - When loading up a wiki page on giraffes the window overlays the left hand side toolbar, and the rest of the screen is white. Appears to be a graphical glitch. See screenshot.

![](https://cloud.githubusercontent.com/assets/8785617/26759247/b05a4832-48ad-11e7-9d6f-c1989c2ef7ca.jpg)

**Comment by Aniket21mathur** [comment]
@pro-panda I think it is fixed in  #22.
Thanks :smile:
