### ISSUE TITLE
Use distro specific Beautiful Soup

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/infoslicer#33]
Remove copies of `BeautifulSoup` and use distro specific library.

@quozl this is different from #29 but with this fixed they'll be no need for #29. 
Would you recommend closing #29 and tracking this instead?

**Comment by quozl** [comment]
Can only remove them if they are unchanged from the original.  That's something that would have to be determined.  My answer in #29 gave potential plans, of which #33 is just one of them.  I don't see why we have another issue for _one_ of the plans.  It confuses.
