### ISSUE TITLE
Error on activity start

### ISSUE THREAD

**Issue by iamutkarshtiwari** [sugarlabs/infoslicer#4]
On downloading and running the "Infoslicer' activity from activity.sugarlabs.org to my sugar-build I get this error https://paste.fedoraproject.org/397381/46981260/

**Comment by quozl** [comment]
"The paste you are looking for does not exist".

**Comment by iamutkarshtiwari** [comment]
It seems that there was some issue with my sugar-build, not InfoSlicer. Sorry
