### ISSUE TITLE
Images are added twice

### ISSUE THREAD

**Issue by iamutkarshtiwari** [sugarlabs/infoslicer#5]
**Steps to reproduce:**
_Open Info Slicer
Go to the edit view
Click on the images icon
Drag and drop an image to the article_

**Issue:**
The image is added twice

**Expected behaviour:**
Add the image just once

![desktop-animation](https://cloud.githubusercontent.com/assets/6258810/18139845/bc2fd75a-6fd0-11e6-8232-270dffb9ee4f.gif)

**Comment by iamutkarshtiwari** [comment]
This PR https://github.com/sugarlabs/infoslicer/pull/6 fixes this issue.

**Comment by iamutkarshtiwari** [comment]
@walterbender Ping

**Comment by rhl-bthr** [comment]
Fixed in #6
